language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mustafa78/docker-example -f Dockerfile.dev .

script:
  - docker run -e CI=true mustafa78/docker-example npm run test